// k6 load generator for cosmos-edge-serve.
//
// One invocation = one cell of the benchmark grid (one profile at one concurrency
// level). The runbook loops over the grid; the script itself stays simple and
// records exactly what it was told to do, so a summary file can never be
// misattributed to a configuration it did not run.
//
//   k6 run -e BASE_URL=http://localhost:8000 -e PROFILE=a -e VUS=4 \
//          -e DURATION=5m -e OUT=results/a-vu4.json loadtest/load.js
//
// Runs on the EC2 instance against localhost. Driving load from a laptop would
// fold WAN jitter into every p95 sample — see docs/CLAUDE.md, "Load generation
// runs on the EC2 instance".
//
// On EC2 (Linux):
//   docker run --rm --network host -v "$PWD:/work" -w /work \
//     -e BASE_URL=http://localhost:8000 ... grafana/k6 run loadtest/load.js
//
// Dry-running on the Windows dev laptop: `--network host` does NOT bridge to the
// host on Docker Desktop, so use `-e BASE_URL=http://host.docker.internal:8000`
// and drop `--network host`. Also drop MAX_NEW_TOKENS to ~32 — NF4 on the 6 GB
// 3060 runs at 0.6-2.9 tok/s, so a 256-token request takes minutes. Local
// numbers are for proving the harness, never for publishing.
//
// No remote imports. jslib.k6.io would be a network dependency at script-init
// time on a paid instance, and a DNS hiccup there is a failed benchmark run, not
// a cosmetic problem. Everything this needs is written out below.

import http from 'k6/http';
import { check, sleep } from 'k6';
import { Counter, Trend } from 'k6/metrics';

// ---------------------------------------------------------------------------
// Media. Read once at init; every VU shares the buffer.
//
// These are generated by scripts/make_assets.py and are NOT committed, so a
// missing file here means that step was skipped. k6 fails loudly at init, which
// is the right moment for it to fail — before any GPU time is spent.
// ---------------------------------------------------------------------------
const IMAGE = open('../assets/sample.jpg', 'b');
const VIDEO = open('../assets/sample.mp4', 'b');

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------
const BASE_URL = (__ENV.BASE_URL || 'http://localhost:8000').replace(/\/$/, '');
const PROFILE = (__ENV.PROFILE || 'a').toLowerCase();
const MEDIA = (__ENV.MEDIA || 'image').toLowerCase();
const VUS = parseInt(__ENV.VUS || '1', 10);
const DURATION = __ENV.DURATION || '5m';
const OUT = __ENV.OUT || 'results/summary.json';

// Profile A is the headline: 256 tokens, comparable p50/p95, a full sweep in
// minutes. Profile B is the honest one: 1024 tokens of real chain-of-thought.
// Both are published — see docs/CLAUDE.md, "Benchmark shape".
const PROFILE_TOKENS = { a: 256, b: 1024 };
const MAX_NEW_TOKENS = parseInt(__ENV.MAX_NEW_TOKENS || PROFILE_TOKENS[PROFILE] || '256', 10);

const PROMPTS = {
  image: 'Describe this scene. Is it safe for a vehicle to proceed straight ahead?',
  video: 'What happens in this video? Describe the motion.',
};

// The client timeout must sit ABOVE the server's COSMOS_REQUEST_TIMEOUT_S, not
// below it. k6's default is 60s, which at profile B would fail every request
// client-side and pin the blame on a service that was working fine. The server
// owns the timeout decision; the client only needs to outlast it.
const REQUEST_TIMEOUT = __ENV.REQUEST_TIMEOUT || '960s';

// In-flight requests are allowed to finish after the duration expires. k6's
// 30s default would cut off exactly the slow requests — the ones under the
// deepest queue — and dropping them would flatter p95 by construction. The cost
// is that wall clock can overrun by up to one request; that is the cheaper error.
const GRACEFUL_STOP = __ENV.GRACEFUL_STOP || '900s';

// ---------------------------------------------------------------------------
// Metrics
//
// http_req_duration alone cannot separate queueing from compute, and that
// decomposition is the entire story this benchmark exists to tell: with one
// serial GPU worker, latency under concurrency is mostly other people's
// requests. So the server's own timing breakdown is pulled out of the response
// body and recorded alongside the wire latency.
// ---------------------------------------------------------------------------
const e2eLatency = new Trend('cosmos_e2e_ms', true);
const queueWait = new Trend('cosmos_queue_wait_ms', true);
const preprocess = new Trend('cosmos_preprocess_ms', true);
const generate = new Trend('cosmos_generate_ms', true);
const tokensPerSecond = new Trend('cosmos_tokens_per_second');
const outputTokens = new Trend('cosmos_output_tokens');

const okRequests = new Counter('cosmos_ok');
const queueFull = new Counter('cosmos_queue_full_503');
const timedOut = new Counter('cosmos_timeout_504');
const truncated = new Counter('cosmos_truncated');
const hardErrors = new Counter('cosmos_hard_errors');

export const options = {
  scenarios: {
    sweep: {
      executor: 'constant-vus',
      vus: VUS,
      duration: DURATION,
      gracefulStop: GRACEFUL_STOP,
    },
  },
  // Fixed duration rather than fixed iterations, because wall clock is what
  // costs money. A fixed iteration count has unbounded cost if the model turns
  // out slower than assumed, which is precisely the unknown this benchmark is
  // being run to resolve. The iteration count is reported so percentiles are
  // honest about how many samples they came from.
  summaryTrendStats: ['min', 'med', 'avg', 'p(90)', 'p(95)', 'p(99)', 'max', 'count'],
  // k6 kills setup() after 60s by default, which would abort the health wait long
  // before a cold model load finishes (84s on the 3060, and that is after the
  // weights are already cached). This has to cover the health poll AND the warmup
  // request, which at profile B is itself minutes.
  setupTimeout: __ENV.SETUP_TIMEOUT || '45m',
  thresholds: {
    // A 503 or a 504 is a correct answer under overload, not a defect, so
    // neither counts here. This threshold fires only on connection failures and
    // 5xx-other — i.e. the service actually broke.
    cosmos_hard_errors: ['count==0'],
  },
  // Long single requests, no browser semantics, nothing to gain from reuse
  // heuristics fighting a 15-minute response.
  noConnectionReuse: false,
  discardResponseBodies: false,
};

function mediaPart() {
  return MEDIA === 'video'
    ? http.file(VIDEO, 'sample.mp4', 'video/mp4')
    : http.file(IMAGE, 'sample.jpg', 'image/jpeg');
}

function fire() {
  return http.post(
    `${BASE_URL}/infer`,
    {
      file: mediaPart(),
      prompt: PROMPTS[MEDIA] || PROMPTS.image,
      max_new_tokens: String(MAX_NEW_TOKENS),
    },
    { timeout: REQUEST_TIMEOUT, tags: { profile: PROFILE, media: MEDIA, vus: String(VUS) } }
  );
}

// ---------------------------------------------------------------------------
// setup(): wait for the model, then burn one throwaway request.
//
// The first video request pays a one-time torchcodec initialisation that has
// nothing to do with steady-state throughput. scripts/kaggle_t4_check.py already
// discards a first run per leg for this reason; the same correction belongs here,
// or the very first sample of every run is an outlier that lands straight in p95.
// ---------------------------------------------------------------------------
export function setup() {
  const deadline = Date.now() + 30 * 60 * 1000;
  let report = null;

  while (Date.now() < deadline) {
    const res = http.get(`${BASE_URL}/health`, { timeout: '30s' });
    if (res.status === 200) {
      try {
        report = res.json('model');
      } catch (err) {
        report = null;
      }
      break;
    }
    console.log(`waiting for ${BASE_URL}/health ... (${res.status || 'no response'})`);
    sleep(5);
  }

  if (report === null) {
    throw new Error(`Service never became healthy at ${BASE_URL}/health`);
  }

  console.log(
    `model ready: ${report.model_class} on ${report.device} ` +
      `(${report.gpu_name || 'CPU'}), dtype=${report.dtype}, quant=${report.quantization}`
  );

  const warm = fire();
  console.log(`warmup request: HTTP ${warm.status} in ${Math.round(warm.timings.duration)}ms`);

  return { report: report, warmup_status: warm.status };
}

export default function () {
  const res = fire();

  // No sleep. The point is saturation: with one serial worker, think time would
  // just make the queue shallower and understate what concurrency actually costs.

  if (res.status === 200) {
    let body = null;
    try {
      body = res.json();
    } catch (err) {
      body = null;
    }

    if (body === null || body.tokens === undefined) {
      hardErrors.add(1);
      check(res, { '200 response parsed as JSON': () => false });
      return;
    }

    okRequests.add(1);
    e2eLatency.add(res.timings.duration);
    queueWait.add(body.timing_ms.queue_wait);
    preprocess.add(body.timing_ms.preprocess);
    generate.add(body.timing_ms.generate);
    tokensPerSecond.add(body.tokens_per_second);
    outputTokens.add(body.tokens.output);
    if (body.truncated) {
      truncated.add(1);
    }

    check(body, {
      'generated at least one token': (b) => b.tokens.output > 0,
      'consumed visual tokens': (b) => b.tokens.visual > 0,
    });
    return;
  }

  if (res.status === 503) {
    // Queue full. An honest answer under overload, and one of the behaviours
    // being measured — not a failure.
    queueFull.add(1);

    // Back off for the Retry-After the service asked for, because otherwise this
    // number means nothing. A VU that retries instantly re-fires the moment the
    // 503 lands, so the count measures how fast k6 can spin, not how much load
    // was offered: a depth-2 dry run produced 34,504 rejections in 45 seconds.
    // Honouring the header is also just what a real client does.
    //
    // JITTER IS NOT COSMETIC. Sleeping exactly Retry-After does two bad things:
    //   1. every rejected VU wakes on the same tick, so the retries arrive as a
    //      synchronised herd rather than as load;
    //   2. Retry-After is 5s and uvicorn's --timeout-keep-alive default is also
    //      5s, so the VU reuses a pooled connection at the exact moment the
    //      server closes it. That race produced 15 spurious "EOF" hard errors in
    //      a dry run — no 5xx, nothing in the service log, just a dead socket.
    //      On EC2 it would have looked like the service faulting under load.
    const retryAfter = parseFloat(res.headers['Retry-After'] || res.headers['retry-after']);
    const backoff = Number.isFinite(retryAfter) && retryAfter > 0 ? retryAfter : 5;
    sleep(backoff * (0.5 + Math.random()));
    return;
  }

  if (res.status === 504) {
    // Server-side timeout: queue wait plus compute exceeded
    // COSMOS_REQUEST_TIMEOUT_S. Recorded rather than hidden, because a run full
    // of these means the timeout was sized wrong for the profile and the table
    // must not be published as if it were latency data.
    timedOut.add(1);
    return;
  }

  hardErrors.add(1);
  console.error(`HTTP ${res.status}: ${String(res.body).slice(0, 300)}`);
}

// ---------------------------------------------------------------------------
// handleSummary(): write the machine-readable summary that render_results.py
// consumes, plus a short human-readable block on stdout.
//
// --summary-export is deprecated; this is the supported path and it also lets
// the run's own configuration be embedded in the file, so a summary can never
// be read as belonging to a different cell of the grid.
// ---------------------------------------------------------------------------
function counter(data, metric) {
  const m = data.metrics[metric];
  return m && m.values ? m.values.count || 0 : 0;
}

export function handleSummary(data) {
  const completed = counter(data, 'cosmos_ok');

  const summary = {
    config: {
      profile: PROFILE,
      media: MEDIA,
      vus: VUS,
      duration: DURATION,
      max_new_tokens: MAX_NEW_TOKENS,
      base_url: BASE_URL,
      request_timeout: REQUEST_TIMEOUT,
      graceful_stop: GRACEFUL_STOP,
    },
    // The load report from /health, captured in setup(). A latency table that
    // has been separated from the hardware that produced it is worthless, so it
    // travels inside the same file.
    model: data.setup_data ? data.setup_data.report : null,
    counts: {
      completed: completed,
      queue_full_503: counter(data, 'cosmos_queue_full_503'),
      timeout_504: counter(data, 'cosmos_timeout_504'),
      truncated: counter(data, 'cosmos_truncated'),
      hard_errors: counter(data, 'cosmos_hard_errors'),
      checks_failed: data.metrics.checks ? data.metrics.checks.values.fails || 0 : 0,
    },
    latency_ms: {
      e2e: data.metrics.cosmos_e2e_ms ? data.metrics.cosmos_e2e_ms.values : null,
      queue_wait: data.metrics.cosmos_queue_wait_ms
        ? data.metrics.cosmos_queue_wait_ms.values
        : null,
      preprocess: data.metrics.cosmos_preprocess_ms
        ? data.metrics.cosmos_preprocess_ms.values
        : null,
      generate: data.metrics.cosmos_generate_ms ? data.metrics.cosmos_generate_ms.values : null,
    },
    throughput: {
      tokens_per_second: data.metrics.cosmos_tokens_per_second
        ? data.metrics.cosmos_tokens_per_second.values
        : null,
      output_tokens: data.metrics.cosmos_output_tokens
        ? data.metrics.cosmos_output_tokens.values
        : null,
      wall_clock_ms: data.state ? data.state.testRunDurationMs : null,
    },
    raw_http_req_duration: data.metrics.http_req_duration
      ? data.metrics.http_req_duration.values
      : null,
  };

  const lines = [];
  const e2e = summary.latency_ms.e2e;
  lines.push('');
  lines.push(`profile ${PROFILE.toUpperCase()} · ${MEDIA} · ${VUS} VU · ${MAX_NEW_TOKENS} tok`);
  lines.push(`  completed        ${completed}`);
  if (e2e) {
    lines.push(`  p50 / p95 (s)    ${(e2e.med / 1000).toFixed(1)} / ${(e2e['p(95)'] / 1000).toFixed(1)}`);
  }
  if (summary.latency_ms.queue_wait) {
    const q = summary.latency_ms.queue_wait;
    lines.push(`  queue wait (s)   ${(q.med / 1000).toFixed(1)} med, ${(q['p(95)'] / 1000).toFixed(1)} p95`);
  }
  if (summary.throughput.tokens_per_second) {
    lines.push(`  tok/s            ${summary.throughput.tokens_per_second.med.toFixed(1)} med`);
  }
  lines.push(
    `  503 / 504        ${summary.counts.queue_full_503} / ${summary.counts.timeout_504}`
  );
  lines.push(`  hard errors      ${summary.counts.hard_errors}`);
  lines.push(`  written to       ${OUT}`);
  lines.push('');

  const out = {};
  out[OUT] = JSON.stringify(summary, null, 2);
  out.stdout = lines.join('\n');
  return out;
}
